### PR TITLE
script: Add condition for html snippets, warn on missing template

### PR DESCRIPTION
**Pull request by kappapiana**
Quick & dirty, but works

### CODE REVIEW

**Comment by kappapiana** [comment]
> good job, but please always put double quotes around variable names :)

I tought I had...

**Comment by kappapiana** [comment]
Made a better job now?

**Comment by kappapiana** [comment]
There is another patch with only clarification as to the content.

**Comment by alpianon** [comment]
> There is another patch with only clarification as to the content.

yes but the help text echoed by the command should be updated, too

**Pull request merged**
